port: 19129
mysql-host: <db_host>
mysql-user: <db_user>
mysql-password: <db_pass>
mysql-database: hso2
debug: true
indexRes: 9
indexCharPar: 0
exp: 10
lvmax: 200
allow_ip_client: 50
time_login: 10000
event: 0
